[tool.poetry]
name = "pythonproject11"
version = "0.1.0"
description = ""
authors = ["Oksana Konkina <oksanka.808@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
